## Collaborative Filtering Based Recommendation system
This is a similarity based recommendater system

In [1]:
# import python libraries
import pandas as pd
import numpy as np

In [12]:
# import datasets
books = pd.read_csv('py_book_list.csv')
ratings = pd.read_csv('Ratings_py.csv')
users = pd.read_csv('users.csv')

In [6]:
ratings.head()

  User-ID  b_id  Ratings
0     NaN   NaN      NaN
1   user1  b_11     10.0
2   user2  b_12      0.0
3   user3  b_13      0.0
4   user4  b_14      5.0

In [5]:
books.head()

  b_id                                      Name of books          Author
0  b_1                    Best Python Books for Beginners  Dwayne Johnson
1  b_2  Best Python Book for Beginners: Python Crash C...   Eric Matthews
2  b_3  Automate the Boring Stuff with Python, 2nd Edi...     Al Sweigart
3  b_4  Best Book for Job Interview Prep: Elements of ...      Adnan Aziz
4  b_5  Learn Python in One Day and Learn It Well (2nd...      Jamie Chan

In [13]:
# merge 2 datasets on basis of b_id
ratings_with_books = ratings.merge(books,on='b_id')

In [9]:
# implement pivot table to accomplish the data in necessary format
pt = ratings_with_books.pivot_table(index='Name of books', columns='User-ID', values='Ratings')

In [14]:
# Replace NA values with 0
pt.fillna(0,inplace=True)
pt.head()

User-ID,user1,user10,user11,user12,user13,user14,user15,user16,user17,user18,...,user46,user47,user48,user49,user5,user50,user6,user7,user8,user9
Name of books,,,,,,,,,,,,,,,,,,,,,
"Automate the Boring Stuff with Python, 2nd Edition: Practical Programming for Total Beginners",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Best Advanced Python Book: Fluent Python: Clear, Concise, and Effective Programming",10.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Best Book for Job Interview Prep: Elements of Programming Interviews in Python: The Insiders' Guide,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Best Book for Practical Learning: Learn Python the Hard Way (3rd Edition),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Best Free Python Book: A Byte of Python,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0